### ISSUE TITLE
時間の巻き戻し機能（巻戻し時間指定）の追加希望

### ISSUE THREAD

**Issue by tksugimoto** [negokaz/chrome-redmine-work-tracker#2]
今、計測時間を0にする機能がありますが、0にするしかなく一定時間だけ減らすということができません。

例えば休み時間や会議時間もタイマーを動かし続けてしまった場合など、その時間分カウントから減らせたら良いと思います。

よろしくお願いします。

**Comment by negokaz** [comment]
I implemented it ! #3
